global:
  scrape_interval: 15s   # how often to scrape targets

scrape_configs:
  # Monitor Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Monitor Node Exporter
  - job_name: "node"
    static_configs:
      - targets: ["172.31.45.115:9100"]

  # Monitor Nginx Exporter
  - job_name: "nginxexporter"
    static_configs:
      - targets: ["172.31.45.115:9113"]

  # Monitor App
  - job_name: "app"
    static_configs:
      - targets: ["15.206.168.127:80"]

rule_files:
  - "/etc/prometheus/alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]